### ISSUE TITLE
Launching Cloudformation stack issue

### ISSUE THREAD

**Issue by Taity045** [aws-els-cpt/eks#13]
Experiencing issues launching stack kindly view image in the link below

 https://drive.google.com/file/d/1WoRSbR92w7PBIlrkJLAE4MWORzU2vMeI/view?usp=sharing

**Comment by chenichu** [comment]
Hi @Taity045 ,

Please kindly try again, the CloudFormation template should now be available again.

Thanks

**Comment by Taity045** [comment]
Yes thanks
